package io.github.rsgarrido.sazanami.ui.theme

import androidx.compose.ui.graphics.Color

val SazanamiAccent = Color(0xFFFFB866)
val SazanamiOnAccent = Color(0xFF2B1700)
val SazanamiAccentContainer = Color(0xFF4A2B0D)
val SazanamiOnAccentContainer = Color(0xFFFFDDB8)

val SazanamiBackground = Color(0xFF0B0E11)
val SazanamiSurface = Color(0xFF101418)
val SazanamiSurfaceLow = Color(0xFF151A1F)
val SazanamiSurfaceContainer = Color(0xFF1A2026)
val SazanamiSurfaceHigh = Color(0xFF20272E)
val SazanamiSurfaceHighest = Color(0xFF283039)
val SazanamiOnSurface = Color(0xFFF0F2F4)
val SazanamiOnSurfaceVariant = Color(0xFFB7C0C8)
val SazanamiOutline = Color(0xFF7B858E)
val SazanamiOutlineVariant = Color(0xFF343C44)

val SazanamiLightPrimary = Color(0xFF97500B)
val SazanamiLightPrimaryContainer = Color(0xFFF5E0C8)
val SazanamiLightBackground = Color(0xFFF7F5F1)
val SazanamiLightSurface = Color(0xFFFFFCF8)
val SazanamiLightOnSurface = Color(0xFF211B16)
val SazanamiLightSurfaceLow = Color(0xFFFFFCF8)
val SazanamiLightSurfaceContainer = Color(0xFFF3F0EB)
val SazanamiLightSurfaceHigh = Color(0xFFECE8E2)
val SazanamiLightSurfaceHighest = Color(0xFFE4DED7)
val SazanamiLightSurfaceVariant = Color(0xFFECE6DE)
val SazanamiLightOnSurfaceVariant = Color(0xFF5C5148)
val SazanamiLightOutline = Color(0xFF82776D)
val SazanamiLightOutlineVariant = Color(0xFFCEC5BA)
val SazanamiLightSecondary = Color(0xFF4A625D)
val SazanamiLightOnSecondary = Color(0xFFFFFFFF)
val SazanamiLightSecondaryContainer = Color(0xFFDFD8CF)
val SazanamiLightOnSecondaryContainer = Color(0xFF302C26)
val SazanamiLightTertiary = Color(0xFF536046)
val SazanamiLightOnTertiary = Color(0xFFFFFFFF)
val SazanamiLightTertiaryContainer = Color(0xFFDBE7CA)
val SazanamiLightOnTertiaryContainer = Color(0xFF182313)
val SazanamiLightError = Color(0xFFBA1A1A)
val SazanamiLightOnError = Color(0xFFFFFFFF)
val SazanamiLightErrorContainer = Color(0xFFFFDAD6)
val SazanamiLightOnErrorContainer = Color(0xFF410002)
val SazanamiLightInverseSurface = Color(0xFF34302B)
val SazanamiLightInverseOnSurface = Color(0xFFF9F3ED)
